function dflowData = importDflowFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CONDITION10001 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CONDITION10001 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  condition10001 = importfile("/Users/hjhuang/Dropbox (Personal)/_MANUSCRIPTS/_Cesar/SP controller testing data/condition10001.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Mar-2021 00:21:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 80);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TimeStamp", "FrameNumber", "LASIPosX", "LASIPosY", "LASIPosZ", "RASIPosX", "RASIPosY", "RASIPosZ", "LPSIPosX", "LPSIPosY", "LPSIPosZ", "RPSIPosX", "RPSIPosY", "RPSIPosZ", "LKNEPosX", "LKNEPosY", "LKNEPosZ", "LTHIPosX", "LTHIPosY", "LTHIPosZ", "LANKPosX", "LANKPosY", "LANKPosZ", "LTIBPosX", "LTIBPosY", "LTIBPosZ", "LTOEPosX", "LTOEPosY", "LTOEPosZ", "LHEEPosX", "LHEEPosY", "LHEEPosZ", "RKNEPosX", "RKNEPosY", "RKNEPosZ", "RTHIPosX", "RTHIPosY", "RTHIPosZ", "RANKPosX", "RANKPosY", "RANKPosZ", "RTIBPosX", "RTIBPosY", "RTIBPosZ", "RTOEPosX", "RTOEPosY", "RTOEPosZ", "RHEEPosX", "RHEEPosY", "RHEEPosZ", "FP1CopX", "FP1CopY", "FP1CopZ", "FP1ForX", "FP1ForY", "FP1ForZ", "FP1MomX", "FP1MomY", "FP1MomZ", "FP2CopX", "FP2CopY", "FP2CopZ", "FP2ForX", "FP2ForY", "FP2ForZ", "FP2MomX", "FP2MomY", "FP2MomZ", "Channel1Anlg", "Channel2Anlg", "Channel3Anlg", "Channel4Anlg", "Channel5Anlg", "Channel6Anlg", "Channel7Anlg", "Channel8Anlg", "Channel9Anlg", "Channel10Anlg", "Channel11Anlg", "Channel12Anlg"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dflowData = readtable(filename, opts);

end